language: erlang
otp_release:
- 19.0
script: "./travis_script.sh"
env:
  secure: rjmrtM/YNJySA7F9jBprk6tH8Upq8KGOQaM7iSOEC24s9zbYGRQDUFM44D7CZYmwCkiTV6mP1kNARbcxE/QnclG2sdQ7fTjJRxWI44+IrJvdWxJTOIOUYzCALr8HJBj5RZ+G75zMiDz3uZPFOuGX3do+TmHMvIdYe9S+BjRYPCrOqGVkAIWbY17c/t/+bZsU8N5KvosSFVswLqa2/gLD+0a9G0scDURfLKF3senimzQRJafTqq7Dph1T1nAPxmtPVOqvLkR2XOlpeXPLlOHj6Pdgh2Q2YPeNDa3aFNZr8hiHDdGRDTg7R8oUuqlOCK6lRCuFmmD/i5iszkHUkNq5PHhoz2BWzn69Eaiogjr4F42bDx2DR1l1hdb0XpulZx0DF9O9WZ0sT9WNZ0G9ReAygjx0/ud6vIHZ7fxGdFz9US1OAisCKbMaoqzHX8YyTkeVmxMxbIdF4J9dGKDkV97VCbOVDkQYPidHxX8yyEs8X8bIssTpA1aB+5a8jaVkdxfSyV3fCw+mNYyQbLKFXzXMk1Z1qLkdie8nq45I7XAgK/u1vVqsBeHdNs3k3+c7fVDVfGa0wSTenFLgos9sbX7UdXBvP+7SH4Kczn2dFBO/t2HL5HarwZM43hs011GnTK61My/ch7bISXdxqS80xNJRCLwhVlp4NsRmEuJh1NexS0M=
